### ISSUE TITLE
Our Projects - DIEMS Website

### ISSUE THREAD

**Issue by mayank-phadke** [dietms/dietms.github.io#10]
'DIEMS website' refers to dietms.org or dietms.github.io?
in any case, upload a screenshot of the website and make it as the background instead of the current thumbnail. 

Also add more technical stuff(at least background images) instead of the default templates

**Comment by aditya-konarde** [comment]
1. 'DIEMS website' refers to the college website i.e. dietms.org
2. A screenshot of the website would be too large to fit as the background. And why would we want to add a screenshot as the background? :grin: 
   3.Project screenshots will be added to the project section once our first activity is over
