### ISSUE TITLE
Create a blog using jekyll and link it properly in the navbar

### ISSUE THREAD

**Issue by aditya-konarde** [dietms/dietms.github.io#16]
The current blog link redirects to a page that says its under construction. The jekyll-powered blog is supposedly up at dietms/blog. 

Anyone interested in working on this issue should assure that the blog works, then properly link the blog to the site's top navigation bar.

**Comment by aniarya82** [comment]
I have addressed this issue by creating a pull request at dietms/blog repo.

**Comment by aditya-konarde** [comment]
@aniarya82 I approved your pull request there, but the blog doesn't seem to be working at https://dietms.github.io/blog/ . Are we missing something?

**Comment by aniarya82** [comment]
Once check the setting of both repo, the Github Pages section. There should be line saying "Your site is published at http://dietms.github.io. And similarly in dietms/blog repo setting you should see "Your site is published at http://dietms.github.io/blog/.

**Comment by aditya-konarde** [comment]
@aniarya82 looks like I accidentally messed up some pull request and the changes got deleted. I have opened another issue there. Please check it out. Shall I mark this one as resolved now? As its an issue with another repo.

**Comment by aniarya82** [comment]
Yeah mark this one resolved. And I will take a look at the other issue and get back to you in a moment.
