### ISSUE TITLE
Header not visible on the teams.html

### ISSUE THREAD

**Issue by deshmukhmayur** [dietms/dietms.github.io#4]
The header/navbar is not visible on the teams.html page as the background and the navbar text is of the same color.
Either the text color needs to be changed or the page background.
Which one do you think?

**Comment by aditya-konarde** [comment]
The header is transparent, i tried changing it to navbar-inverse but that changes the font and looks inconsistent. Any solution? I feel lets change the navbar color.

**Comment by deshmukhmayur** [comment]
Ohk I'll try both.
But in my opinion, a colored/textured background will look good and consistent with the homepage.

**Comment by mayank-phadke** [comment]
white background suits the teams page but i think its too simple
maybe change the background instead of the text
i like the header as it is

**Comment by deshmukhmayur** [comment]
Ohk @mayank-phadke I'll try a gradient background or maybe a design. Got any ideas?

**Comment by mayank-phadke** [comment]
@deshmukhmayur something happened and now its fixed
At least on the mobile version

**Comment by aditya-konarde** [comment]
Fixed with your latest commit.
