### ISSUE TITLE
'Blog' page missing

### ISSUE THREAD

**Issue by mayank-phadke** [dietms/dietms.github.io#7]
design the basic look of the page
i can start blogging

**Comment by deshmukhmayur** [comment]
@mayank-phadke I'll add a repo with Jekyll preinstalled. Just give me a few hours.

**Comment by aditya-konarde** [comment]
Added coming soon page. Shall we close the issue now?

**Comment by mayank-phadke** [comment]
just add the basic layout of page
i will edit it later
